### ISSUE TITLE
论文里公式(1)的dimension貌似对不上？

### ISSUE THREAD

**Issue by guotong1988** [xxj96/SQLNet#15]
![_20180123153228](https://user-images.githubusercontent.com/4702353/35263248-f9bccf56-0052-11e8-9fde-8695ac1c9bee.png)

E_col是[batch_size, column_num, hidden_size]
E_Q是[batch_size, question_words_num, hidden_size]

@xiaojunxu 多谢！！！

**Comment by guotong1988** [comment]
@xiaojunxu 可否留个邮箱？多谢！！！

**Comment by xiaojunxu** [comment]
E_Q is the embedding of the input question, so it's [batch_size, hidden_size]; E_col is the embedding of a specific column, so it's also [batch_size, hidden_size].

**Comment by guotong1988** [comment]
我再看看
