### ISSUE TITLE
这三个unsqueeze再过MLP的操作实在不懂为啥要这样啊……

### ISSUE THREAD

**Issue by guotong1988** [xxj96/SQLNet#17]
https://github.com/xiaojunxu/SQLNet/blob/master/sqlnet/model/modules/sqlnet_condition_predict.py#L233-L235
```
h_ext = h_str_enc.unsqueeze(1).unsqueeze(1)
g_ext = g_str_s.unsqueeze(3)
col_ext = col_emb.unsqueeze(2).unsqueeze(2)
```

@xiaojunxu 多谢！！！

**Comment by xiaojunxu** [comment]
h_ext : [B, INPUT_TOK_NUM, N_H]
g_ext : [B, IDX, OUTPUT_TOK_NUM, N_H]
col_ext : [B, IDX, N_H]
where IDX refers to the maximum number of predicted columns (which is 4), INPUT_TOK_NUM refers to the input token number and OUTPUT_TOK_NUM refers to the length of output sequence. So our output is supposed to be in the shape of [B, IDX, OUTPUT_TOK_NUM, INPUT_TOK_NUM].

**Comment by guotong1988** [comment]
多谢，我再看看

**Comment by guotong1988** [comment]
其实主要不懂为啥弄成同等维数相加 就能是pointer net了

**Comment by guotong1988** [comment]
> our output is supposed to be in the shape of [B, IDX, OUTPUT_TOK_NUM, INPUT_TOK_NUM]

为什么？

**Comment by guotong1988** [comment]
这三个加一起的含义（设计原由）就是想要这三个都对cond_str_score产生影响吗？
