### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by deepanshib** [xxj96/SQLNet#37]
while i m running the extract_vocab.py file... the memory used is pushed to 98% and i m scared to continue running the script and hence i had to stop the script.
Can anyone help 
@xiaojunxu what should i do to deal with this?

**Comment by ramapochinapeddi** [comment]
set USE_SMALL = true and try again; it loads small data set

**Comment by artisvirat** [comment]
@deepanshib Did use_small=True work for you? It didn't for me.

**Comment by deepanshib** [comment]
@artisvirat  yeah it worked !

if it didnt work for you try this 
  go to sqlnet/utils.py
  Almost all functions have use_small value as False by default in arguments. Change the default value to 
  True and then run the code.

**Comment by shambhaviparashar** [comment]
@artisvirat do you remember what worked for you?

**Comment by shambhaviparashar** [comment]
@deepanshib how to you know that memory usage is 98%?
